# Generated by Django 4.2.6 on 2024-05-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('employee_name', models.CharField(max_length=50)),
                ('employee_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('attendance_status', models.CharField(choices=[('S', 'Sick'), ('L', 'Late'), ('P', 'Present'), ('A', 'Absent')], max_length=1)),
            ],
        ),
    ]
