# Generated by Django 4.2.6 on 2024-05-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='attendance_status',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('S', 'Sick')], max_length=1),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='employee_id',
            field=models.CharField(max_length=10),
        ),
    ]
